### ISSUE TITLE
Option for filtering "archived" cards.

### ISSUE THREAD

**Issue by debrando** [jonabc/linked-project-columns#17]
In order to *declutter* our projects boards without losing the context, we frequently use the *archive card* feature. Unluckily, as far as I see the *archived* status is ignored during the *mirroring* and also there is no way to manage it by filtering because it's not a tag. As a result, the target board is clogged by all the archived issue from source columns.

It would be really useful if it could be possible to ignore archived cards on source columns, or at least mirror also the *archived* state so the cards would be hidden on target column.

**Comment by jonabc** [comment]
@debrando good call!  

> It would be really useful if it could be possible to ignore archived cards on source columns, or at least mirror also the archived state so the cards would be hidden on target column.

👍  the action should not copy archived cards, or at least should persist the archived flag.

I had done some quick testing early in the project and believed that archived cards weren't copied at all.  If you have time to do some work here and open a PR, please do!  Otherwise I'll get to it soon-ish.
